# Imagen base
FROM python:3.11-slim

# Establecer directorio de trabajo
WORKDIR /app

COPY  Flask/ /app/

# Instalar dependencias
RUN pip install --no-cache-dir -r requirements.txt

CMD ["python", "app.py"]